[build] allow enable systemd template service

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -1512,19 +1512,21 @@ enable_service() {
   local target="$2"
   local target_dir=$INSTALL
 
-  [ -f "$target_dir/$unit_dir/$unit" ] || die "ERROR: cannot enable non-existent service $target_dir/$unit_dir/$unit"
+  local clean_unit=$(echo "${unit}" | sed 's/@.*\.service$/@.service/')
+
+  [ -f "$target_dir/$unit_dir/$clean_unit" ] || die "ERROR: cannot enable non-existent service $target_dir/$unit_dir/$unit"
 
   if [ -z "$target" ] ; then
-    for target in `grep '^WantedBy' $target_dir/$unit_dir/$unit | cut -f2 -d=` ; do
+    for target in `grep '^WantedBy' $target_dir/$unit_dir/$clean_unit | cut -f2 -d=` ; do
       if [ -n "$target" ]; then
         mkdir -p ${target_dir}/$unit_dir/${target}.wants
-        ln -sf ../${unit} ${target_dir}/$unit_dir/${target}.wants/
+        ln -sf ../${clean_unit} ${target_dir}/$unit_dir/${target}.wants/${unit}
       fi
     done
   fi
-  for target in `grep '^Alias' $target_dir/$unit_dir/$unit | cut -f2 -d=` ; do
+  for target in `grep '^Alias' $target_dir/$unit_dir/$clean_unit | cut -f2 -d=` ; do
     if [ -n "$target" ]; then
-      ln -sf ${unit} ${target_dir}/$unit_dir/${target}
+      ln -sf ${clean_unit} ${target_dir}/$unit_dir/${target}
     fi
   done
 }
